import { MentorProfile, Category, Review, Chat, Message, Transaction } from './types';

export const categories: Category[] = [
  { id: '1', name: 'Career & Tech', icon: '💻', slug: 'career-tech', description: 'Software engineering, product management, career transitions', mentorCount: 124 },
  { id: '2', name: 'Business & Startup', icon: '🚀', slug: 'business-startup', description: 'Entrepreneurship, fundraising, business strategy', mentorCount: 89 },
  { id: '3', name: 'Life Coaching', icon: '🧘', slug: 'life-coaching', description: 'Personal development, motivation, work-life balance', mentorCount: 156 },
  { id: '4', name: 'Finance & Investment', icon: '💰', slug: 'finance-investment', description: 'Stock market, mutual funds, financial planning', mentorCount: 78 },
  { id: '5', name: 'Health & Wellness', icon: '❤️', slug: 'health-wellness', description: 'Nutrition, fitness, mental health support', mentorCount: 112 },
  { id: '6', name: 'Legal Advice', icon: '⚖️', slug: 'legal-advice', description: 'Contract review, compliance, legal consultation', mentorCount: 45 },
  { id: '7', name: 'Education & Exam Prep', icon: '📚', slug: 'education', description: 'UPSC, CAT, GRE, college admissions guidance', mentorCount: 203 },
  { id: '8', name: 'Creative Arts', icon: '🎨', slug: 'creative-arts', description: 'Design, writing, music, photography mentorship', mentorCount: 67 },
  { id: '9', name: 'Relationships', icon: '💝', slug: 'relationships', description: 'Dating advice, family counseling, communication skills', mentorCount: 91 },
  { id: '10', name: 'Astrology & Spiritual', icon: '🌟', slug: 'astrology-spiritual', description: 'Astrology readings, tarot, spiritual guidance', mentorCount: 178 },
];

export const mentors: (MentorProfile & { name: string; avatar: string; email: string })[] = [
  {
    uid: 'mentor-1',
    name: 'Priya Sharma',
    email: 'priya@example.com',
    avatar: '',
    bio: 'Senior Software Engineer at Google with 10+ years of experience. I help engineers crack FAANG interviews and navigate career growth in tech. Specializing in system design, DSA, and leadership development.',
    expertise: ['System Design', 'DSA', 'Career Growth', 'Interview Prep'],
    categories: ['career-tech'],
    pricePerMin: 15,
    rating: 4.9,
    reviewCount: 342,
    isOnline: true,
    isVerified: true,
    totalSessions: 1205,
    languages: ['English', 'Hindi'],
  },
  {
    uid: 'mentor-2',
    name: 'Rahul Verma',
    email: 'rahul@example.com',
    avatar: '',
    bio: 'Chartered Financial Planner with 15 years in wealth management. Expert in mutual funds, stock market analysis, and retirement planning. Let me help you build your financial future.',
    expertise: ['Stock Market', 'Mutual Funds', 'Tax Planning', 'Retirement'],
    categories: ['finance-investment'],
    pricePerMin: 20,
    rating: 4.8,
    reviewCount: 218,
    isOnline: true,
    isVerified: true,
    totalSessions: 890,
    languages: ['English', 'Hindi', 'Gujarati'],
  },
  {
    uid: 'mentor-3',
    name: 'Dr. Anita Desai',
    email: 'anita@example.com',
    avatar: '',
    bio: 'Clinical psychologist and certified life coach. 12 years of experience helping individuals overcome anxiety, build confidence, and find purpose. Warm, empathetic approach to personal growth.',
    expertise: ['Anxiety', 'Confidence Building', 'Work-Life Balance', 'Stress Management'],
    categories: ['life-coaching', 'health-wellness'],
    pricePerMin: 25,
    rating: 4.9,
    reviewCount: 567,
    isOnline: false,
    isVerified: true,
    totalSessions: 2100,
    languages: ['English', 'Hindi', 'Marathi'],
  },
  {
    uid: 'mentor-4',
    name: 'Vikram Singh',
    email: 'vikram@example.com',
    avatar: '',
    bio: 'Serial entrepreneur, 3x founder with 2 successful exits. YC alumni. I mentor early-stage founders on product-market fit, fundraising, and scaling. Passionate about the Indian startup ecosystem.',
    expertise: ['Fundraising', 'Product Strategy', 'Scaling', 'Startup Operations'],
    categories: ['business-startup'],
    pricePerMin: 30,
    rating: 4.7,
    reviewCount: 156,
    isOnline: true,
    isVerified: true,
    totalSessions: 450,
    languages: ['English', 'Hindi'],
  },
  {
    uid: 'mentor-5',
    name: 'Meera Krishnan',
    email: 'meera@example.com',
    avatar: '',
    bio: 'Vedic astrologer with 20 years of practice. Specialized in career astrology, relationship compatibility, and life path readings. Combines traditional wisdom with modern practical advice.',
    expertise: ['Vedic Astrology', 'Career Readings', 'Compatibility', 'Life Path'],
    categories: ['astrology-spiritual'],
    pricePerMin: 10,
    rating: 4.6,
    reviewCount: 892,
    isOnline: true,
    isVerified: true,
    totalSessions: 3400,
    languages: ['English', 'Hindi', 'Tamil'],
  },
  {
    uid: 'mentor-6',
    name: 'Adv. Sneha Patel',
    email: 'sneha@example.com',
    avatar: '',
    bio: 'Corporate lawyer at a top-tier law firm with 8 years of experience. Specializing in contract law, startup legal compliance, and intellectual property. Making legal advice accessible.',
    expertise: ['Contract Law', 'Startup Legal', 'IP Rights', 'Compliance'],
    categories: ['legal-advice'],
    pricePerMin: 35,
    rating: 4.8,
    reviewCount: 134,
    isOnline: false,
    isVerified: true,
    totalSessions: 320,
    languages: ['English', 'Hindi', 'Gujarati'],
  },
  {
    uid: 'mentor-7',
    name: 'Arjun Reddy',
    email: 'arjun@example.com',
    avatar: '',
    bio: 'UPSC CSE AIR 45 (2019). Full-time UPSC mentor helping aspirants with strategy, answer writing, and interview preparation. 200+ students selected in the last 3 years.',
    expertise: ['UPSC Strategy', 'Answer Writing', 'Interview Prep', 'Optional Selection'],
    categories: ['education'],
    pricePerMin: 12,
    rating: 4.9,
    reviewCount: 445,
    isOnline: true,
    isVerified: true,
    totalSessions: 1800,
    languages: ['English', 'Hindi', 'Telugu'],
  },
  {
    uid: 'mentor-8',
    name: 'Kavya Nair',
    email: 'kavya@example.com',
    avatar: '',
    bio: 'UI/UX designer at Figma, previously at Airbnb. I help designers build stunning portfolios, ace design interviews, and transition into product design. Design thinking advocate.',
    expertise: ['UI/UX Design', 'Portfolio Review', 'Design Systems', 'Career Switch'],
    categories: ['creative-arts', 'career-tech'],
    pricePerMin: 18,
    rating: 4.7,
    reviewCount: 198,
    isOnline: true,
    isVerified: true,
    totalSessions: 670,
    languages: ['English', 'Malayalam'],
  },
];

export const sampleReviews: Review[] = [
  {
    id: 'rev-1',
    mentorId: 'mentor-1',
    menteeId: 'user-1',
    menteeName: 'Amit K.',
    menteeAvatar: '',
    rating: 5,
    comment: 'Priya helped me crack my Google interview! Her system design guidance was incredibly detailed and practical. Worth every penny.',
    chatId: 'chat-1',
    createdAt: new Date('2024-12-15'),
  },
  {
    id: 'rev-2',
    mentorId: 'mentor-1',
    menteeId: 'user-2',
    menteeName: 'Neha R.',
    menteeAvatar: '',
    rating: 5,
    comment: 'Best career mentor I have found. She gave me a clear roadmap for transitioning from backend to full-stack. Very patient and knowledgeable.',
    chatId: 'chat-2',
    createdAt: new Date('2024-12-10'),
  },
  {
    id: 'rev-3',
    mentorId: 'mentor-1',
    menteeId: 'user-3',
    menteeName: 'Saurabh M.',
    menteeAvatar: '',
    rating: 4,
    comment: 'Great insights on DSA preparation. Could have been more specific about which topics to focus on for my level.',
    chatId: 'chat-3',
    createdAt: new Date('2024-11-28'),
  },
];

export const sampleChats: Chat[] = [
  {
    id: 'chat-1',
    participants: ['user-demo', 'mentor-1'],
    mentorId: 'mentor-1',
    menteeId: 'user-demo',
    mentorName: 'Priya Sharma',
    menteeName: 'You',
    mentorAvatar: '',
    menteeAvatar: '',
    lastMessage: 'Sure, let me explain the approach for designing a URL shortener...',
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 5),
    status: 'active',
    unreadCount: 2,
  },
  {
    id: 'chat-2',
    participants: ['user-demo', 'mentor-4'],
    mentorId: 'mentor-4',
    menteeId: 'user-demo',
    mentorName: 'Vikram Singh',
    menteeName: 'You',
    mentorAvatar: '',
    menteeAvatar: '',
    lastMessage: 'Your pitch deck looks solid. Let us work on the financial projections next.',
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
    status: 'active',
    unreadCount: 0,
  },
  {
    id: 'chat-3',
    participants: ['user-demo', 'mentor-7'],
    mentorId: 'mentor-7',
    menteeId: 'user-demo',
    mentorName: 'Arjun Reddy',
    menteeName: 'You',
    mentorAvatar: '',
    menteeAvatar: '',
    lastMessage: 'Focus on Polity and Economy for the prelims. I will share study material.',
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    status: 'active',
    unreadCount: 1,
  },
];

export const sampleMessages: Message[] = [
  {
    id: 'msg-0',
    senderId: 'system',
    text: 'Session started. You are being charged ₹15/min.',
    type: 'system',
    timestamp: new Date(Date.now() - 1000 * 60 * 30),
    read: true,
  },
  {
    id: 'msg-1',
    senderId: 'user-demo',
    text: 'Hi Priya! I have an upcoming system design interview at Google. Can you help me prepare?',
    type: 'text',
    timestamp: new Date(Date.now() - 1000 * 60 * 28),
    read: true,
  },
  {
    id: 'msg-2',
    senderId: 'mentor-1',
    text: 'Hey! Absolutely, I would love to help. What level are you interviewing for? L4 or L5?',
    type: 'text',
    timestamp: new Date(Date.now() - 1000 * 60 * 27),
    read: true,
  },
  {
    id: 'msg-3',
    senderId: 'user-demo',
    text: 'L5. I have about 6 years of experience. I am comfortable with basic system design but struggle with distributed systems and scalability questions.',
    type: 'text',
    timestamp: new Date(Date.now() - 1000 * 60 * 25),
    read: true,
  },
  {
    id: 'msg-4',
    senderId: 'mentor-1',
    text: 'Perfect. For L5, they expect you to drive the design independently. Let us start with a classic problem. How would you design a URL shortener like bit.ly?',
    type: 'text',
    timestamp: new Date(Date.now() - 1000 * 60 * 23),
    read: true,
  },
  {
    id: 'msg-5',
    senderId: 'user-demo',
    text: 'I would start with the API design. We need two endpoints - one for creating short URLs and one for redirecting.',
    type: 'text',
    timestamp: new Date(Date.now() - 1000 * 60 * 20),
    read: true,
  },
  {
    id: 'msg-6',
    senderId: 'mentor-1',
    text: 'Good start! But before jumping into APIs, start by clarifying requirements. Ask about scale - how many URLs per day? Read:write ratio? URL expiration? Analytics needed? This shows L5 thinking.',
    type: 'text',
    timestamp: new Date(Date.now() - 1000 * 60 * 18),
    read: true,
  },
  {
    id: 'msg-7',
    senderId: 'mentor-1',
    text: 'Sure, let me explain the approach for designing a URL shortener...',
    type: 'text',
    timestamp: new Date(Date.now() - 1000 * 60 * 5),
    read: false,
  },
];

export const sampleTransactions: Transaction[] = [
  { id: 'txn-1', userId: 'user-demo', amount: 500, type: 'recharge', description: 'Wallet recharge via UPI', paymentId: 'pay_123', createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5) },
  { id: 'txn-2', userId: 'user-demo', amount: -150, type: 'debit', description: 'Chat session with Priya Sharma (10 min)', createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4) },
  { id: 'txn-3', userId: 'user-demo', amount: 1000, type: 'recharge', description: 'Wallet recharge via Card', paymentId: 'pay_456', createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3) },
  { id: 'txn-4', userId: 'user-demo', amount: -300, type: 'debit', description: 'Voice call with Vikram Singh (10 min)', createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2) },
  { id: 'txn-5', userId: 'user-demo', amount: -180, type: 'debit', description: 'Chat session with Arjun Reddy (15 min)', createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24) },
  { id: 'txn-6', userId: 'user-demo', amount: 200, type: 'recharge', description: 'Wallet recharge via UPI', paymentId: 'pay_789', createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12) },
];
